'use strict';
const startedAt=new Date(),startedPerf=performance.now(),metricsEl=document.getElementById('metrics'),collectionNote=document.getElementById('collectionNote'),exportButton=document.getElementById('exportButton'),textButton=document.getElementById('textButton'),exportStatus=document.getElementById('exportStatus'),permissionButton=document.getElementById('permissionButton'),permissionStatus=document.getElementById('permissionStatus'),deviceChooserActions=document.getElementById('deviceChooserActions'),bluetoothButton=document.getElementById('bluetoothButton'),usbButton=document.getElementById('usbButton'),styleSwitch=document.getElementById('styleSwitch'),themeColor=document.getElementById('themeColor'),metricNodes=new Map(),deviceGroups=new Map();
let timeMetricValue=null,displayUpdateTimer=null,exporting=false,restrictedStarted=false,restrictedGranted=false,geoWatchId=null,bluetoothDevice=null,batteryRef=null;
const bluetoothServiceNames={battery_service:'Battery service',device_information:'Device information',generic_access:'Generic access',generic_attribute:'Generic attribute','0000180f-0000-1000-8000-00805f9b34fb':'Battery service','0000180a-0000-1000-8000-00805f9b34fb':'Device information','00001800-0000-1000-8000-00805f9b34fb':'Generic access','00001801-0000-1000-8000-00805f9b34fb':'Generic attribute'};
const usbClassNames={0:'Defined at interface level',1:'Audio',2:'Communications',3:'Human interface',5:'Physical',6:'Imaging',7:'Printer',8:'Mass storage',9:'Hub',10:'CDC data',11:'Smart card',13:'Content security',14:'Video',15:'Personal healthcare',16:'Audio/video',17:'Billboard',18:'USB-C bridge',220:'Diagnostic',224:'Wireless controller',239:'Miscellaneous',254:'Application specific',255:'Vendor specific'};
const pad=n=>String(n).padStart(2,'0'),clean=v=>typeof v==='string'?v.trim():v,valid=v=>{if(v===null||v===undefined)return false;if(typeof v==='number')return Number.isFinite(v);if(typeof v==='string'){const x=v.trim();return x!==''&&!/^(unavailable|unsupported|unknown|null|undefined|n\/a)$/i.test(x)}return typeof v==='boolean'};
const metricKey=(label,key)=>key||String(label).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
function metricInsertTarget(){return metricsEl.querySelector('[data-key="time-of-visit"]')}
function createMetricShell(label,id){const item=document.createElement('article');item.className='metric';item.dataset.key=id;item.dataset.label=label;const labelEl=document.createElement('p');labelEl.className='metric-label';labelEl.textContent=label;item.appendChild(labelEl);return{item,labelEl}}
function setMetric(label,value,key=''){const id=metricKey(label,key);value=clean(value);const existing=metricNodes.get(id);if(!valid(value)){if(existing){existing.item.remove();metricNodes.delete(id)}return null}if(existing&&existing.type==='text'){existing.valueEl.textContent=String(value);existing.item.dataset.exportValue=String(value);if(existing.label!==label){existing.labelEl.textContent=label;existing.item.dataset.label=label;existing.label=label}return existing.valueEl}if(existing){existing.item.remove();metricNodes.delete(id)}const{item,labelEl}=createMetricShell(label,id),valueEl=document.createElement('p');valueEl.className='metric-value';valueEl.textContent=String(value);item.dataset.exportValue=String(value);item.appendChild(valueEl);const target=metricInsertTarget();target?metricsEl.insertBefore(item,target):metricsEl.appendChild(item);metricNodes.set(id,{item,labelEl,valueEl,label,type:'text'});return valueEl}
function setRichMetric(label,key,node,exportValue){const id=metricKey(label,key),existing=metricNodes.get(id);if(existing){existing.item.remove();metricNodes.delete(id)}const{item,labelEl}=createMetricShell(label,id),wrap=document.createElement('div');wrap.className='rich-value';wrap.appendChild(node);item.dataset.exportValue=String(exportValue||'Displayed visually');item.appendChild(wrap);const target=metricInsertTarget();target?metricsEl.insertBefore(item,target):metricsEl.appendChild(item);metricNodes.set(id,{item,labelEl,valueWrap:wrap,label,type:'rich'})}
function getDeviceGroup(id,title){let group=deviceGroups.get(id);if(group)return group;const section=document.createElement('section');section.className='device-group';section.dataset.deviceGroup=id;const kicker=document.createElement('p');kicker.className='device-group-kicker';kicker.textContent='Connected hardware';const heading=document.createElement('h3');heading.className='device-group-title';heading.textContent=title;const list=document.createElement('div');list.className='device-group-list';section.append(kicker,heading,list);const target=metricInsertTarget();target?metricsEl.insertBefore(section,target):metricsEl.appendChild(section);group={section,list};deviceGroups.set(id,group);return group}
function setGroupedMetric(groupId,groupTitle,label,value,key){const id=metricKey(label,key);value=clean(value);const existing=metricNodes.get(id);if(!valid(value)){if(existing){existing.item.remove();metricNodes.delete(id)}return null}const group=getDeviceGroup(groupId,groupTitle);if(existing&&existing.type==='text'){existing.valueEl.textContent=String(value);existing.item.dataset.exportValue=String(value);return existing.valueEl}if(existing){existing.item.remove();metricNodes.delete(id)}const{item,labelEl}=createMetricShell(label,id),valueEl=document.createElement('p');valueEl.className='metric-value';valueEl.textContent=String(value);item.dataset.exportValue=String(value);item.appendChild(valueEl);group.list.appendChild(item);metricNodes.set(id,{item,labelEl,valueEl,label,type:'text'});return valueEl}
function formatDuration(ms){const total=Math.max(0,Math.floor(ms/1000)),hours=Math.floor(total/3600),minutes=Math.floor(total%3600/60),seconds=total%60;return`${pad(hours)}:${pad(minutes)}:${pad(seconds)}`}
function updateTimer(){if(timeMetricValue)timeMetricValue.textContent=formatDuration(performance.now()-startedPerf)}
function languageName(code){if(!valid(code))return null;const base=String(code).split('-')[0].toLowerCase();try{if(typeof Intl.DisplayNames==='function'){const names=new Intl.DisplayNames([navigator.language||'en'],{type:'language'}),name=names.of(base);if(valid(name))return name}}catch(_){}const fallback={en:'English',fr:'French',de:'German',es:'Spanish',it:'Italian',pt:'Portuguese',nl:'Dutch',pl:'Polish',sv:'Swedish',no:'Norwegian',da:'Danish',fi:'Finnish',cs:'Czech',ro:'Romanian',hu:'Hungarian',el:'Greek',tr:'Turkish',ru:'Russian',uk:'Ukrainian',ar:'Arabic',he:'Hebrew',hi:'Hindi',bn:'Bengali',ur:'Urdu',zh:'Chinese',ja:'Japanese',ko:'Korean',th:'Thai',vi:'Vietnamese',id:'Indonesian'};return fallback[base]||null}
function detectDevice(){const ua=navigator.userAgent||'',touchMac=/Macintosh/i.test(ua)&&navigator.maxTouchPoints>1;if(/iPhone/i.test(ua))return'iPhone';if(/iPad/i.test(ua)||touchMac)return'iPad';if(/Android/i.test(ua)&&/Mobile/i.test(ua))return'Android phone';if(/Android/i.test(ua))return'Android tablet';if(/Windows/i.test(ua))return'Windows computer';if(/Macintosh|Mac OS X/i.test(ua))return'Mac';if(/CrOS/i.test(ua))return'Chromebook';if(/Linux/i.test(ua))return'Linux computer';return null}
function detectOS(){const ua=navigator.userAgent||'',touchMac=/Macintosh/i.test(ua)&&navigator.maxTouchPoints>1;let m;if((m=ua.match(/(?:iPhone|CPU(?: iPhone)? OS) ([\d_]+)/i))||(touchMac&&(m=ua.match(/Version\/([\d.]+)/i))))return`iPadOS/iOS ${m[1].replace(/_/g,'.')}`;if((m=ua.match(/Android\s+([\d.]+)/i)))return`Android ${m[1]}`;if((m=ua.match(/Mac OS X\s+([\d_]+)/i)))return`macOS ${m[1].replace(/_/g,'.')}`;if(/Windows NT 10\.0/i.test(ua))return'Windows 10/11';if(/Windows NT 6\.3/i.test(ua))return'Windows 8.1';if(/Windows NT 6\.1/i.test(ua))return'Windows 7';if((m=ua.match(/CrOS [^ ]+ ([\d.]+)/i)))return`ChromeOS ${m[1]}`;if(/Linux/i.test(ua))return'Linux';return null}
function detectBrowser(){const ua=navigator.userAgent||'',checks=[[/EdgiOS\/([\d.]+)/i,'Edge'],[/EdgA?\/([\d.]+)/i,'Edge'],[/OPiOS\/([\d.]+)/i,'Opera'],[/OPR\/([\d.]+)/i,'Opera'],[/CriOS\/([\d.]+)/i,'Chrome'],[/Chrome\/([\d.]+)/i,'Chrome'],[/FxiOS\/([\d.]+)/i,'Firefox'],[/Firefox\/([\d.]+)/i,'Firefox']];for(const[regex,name]of checks){const match=ua.match(regex);if(match)return`${name} ${match[1]}`}if(/Safari/i.test(ua)){const match=ua.match(/Version\/([\d.]+)/i);if(match)return`Safari ${match[1]}`}return null}
function screenOrientation(){try{if(screen.orientation&&valid(screen.orientation.type))return screen.orientation.type.replace(/-/g,' ');if(window.matchMedia){if(matchMedia('(orientation: portrait)').matches)return'Portrait';if(matchMedia('(orientation: landscape)').matches)return'Landscape'}}catch(_){}return null}
function updateDisplayMetrics(){const dpr=Number(window.devicePixelRatio)||1,w=Math.round(screen.width*dpr),h=Math.round(screen.height*dpr);if(w>0&&h>0)setMetric('Screen size',`${w} × ${h} px`,'screen-size');setMetric('Screen orientation',screenOrientation(),'screen-orientation')}
function scheduleDisplayUpdate(){clearTimeout(displayUpdateTimer);displayUpdateTimer=setTimeout(updateDisplayMetrics,100)}
const colorDark=window.matchMedia?matchMedia('(prefers-color-scheme: dark)'):null,colorLight=window.matchMedia?matchMedia('(prefers-color-scheme: light)'):null,contrastMore=window.matchMedia?matchMedia('(prefers-contrast: more)'):null,contrastLess=window.matchMedia?matchMedia('(prefers-contrast: less)'):null,forcedColors=window.matchMedia?matchMedia('(forced-colors: active)'):null;
function updateAppearanceMetrics(){if(colorDark||colorLight)setMetric('Preferred colour scheme',colorDark?.matches?'Dark':colorLight?.matches?'Light':null,'colour-scheme');if(contrastMore||contrastLess||forcedColors)setMetric('Contrast preference',forcedColors?.matches?'High contrast':contrastMore?.matches?'More':contrastLess?.matches?'Less':null,'contrast-preference')}
function listenMedia(query,handler){if(!query)return;if(typeof query.addEventListener==='function')query.addEventListener('change',handler);else if(typeof query.addListener==='function')query.addListener(handler)}
const connection=navigator.connection||navigator.mozConnection||navigator.webkitConnection;
function updateConnectionMetrics(){if(!connection)return;setMetric('Connection type',connection.type,'connection-type');setMetric('Effective connection',connection.effectiveType?String(connection.effectiveType).toUpperCase():null,'effective-connection');setMetric('Estimated downlink',Number.isFinite(connection.downlink)&&connection.downlink>0?`${connection.downlink} Mbps`:null,'estimated-downlink');setMetric('Estimated latency',Number.isFinite(connection.rtt)&&connection.rtt>=0?`${connection.rtt} ms`:null,'estimated-latency');setMetric('Data saver',typeof connection.saveData==='boolean'?(connection.saveData?'On':'Off'):null,'data-saver')}
function updateBatteryMetrics(){if(!batteryRef)return;setMetric('Battery',Number.isFinite(batteryRef.level)&&batteryRef.level>=0&&batteryRef.level<=1?`${Math.round(batteryRef.level*100)}%`:null,'battery');setMetric('Charging',typeof batteryRef.charging==='boolean'?(batteryRef.charging?'Yes':'No'):null,'charging')}
async function initBatteryMetrics(){if(typeof navigator.getBattery!=='function')return;try{batteryRef=await navigator.getBattery();if(!batteryRef)return;updateBatteryMetrics();batteryRef.addEventListener?.('levelchange',updateBatteryMetrics);batteryRef.addEventListener?.('chargingchange',updateBatteryMetrics)}catch(_){}}
function addInitialMetrics(){const localeOptions={year:'numeric',month:'long',day:'numeric'},timeOptions={hour:'2-digit',minute:'2-digit',second:'2-digit'},platform=navigator.userAgentData?.platform||navigator.platform;collectionNote.textContent=`Accession ${startedAt.getFullYear()} · ${pad(startedAt.getMonth()+1)}${pad(startedAt.getDate())}-${pad(startedAt.getHours())}${pad(startedAt.getMinutes())}${pad(startedAt.getSeconds())}`;setMetric('Device',detectDevice(),'device');setMetric('Operating system',detectOS(),'operating-system');setMetric('Platform',platform,'platform');setMetric('Browser',detectBrowser(),'browser');setMetric('Preferred language',languageName(navigator.language),'preferred-language');if(Array.isArray(navigator.languages)&&navigator.languages.length>1)setMetric('Browser languages',navigator.languages.join(', '),'browser-languages');try{setMetric('Timezone',Intl.DateTimeFormat().resolvedOptions().timeZone,'timezone')}catch(_){}setMetric('Local date',startedAt.toLocaleDateString(undefined,localeOptions),'local-date');setMetric('Arrival time',startedAt.toLocaleTimeString(undefined,timeOptions),'arrival-time');updateDisplayMetrics();if(typeof navigator.maxTouchPoints==='number')setMetric('Touch support',navigator.maxTouchPoints>0?'Yes':'No','touch-support');updateAppearanceMetrics();if(Number.isFinite(navigator.deviceMemory)&&navigator.deviceMemory>0)setMetric('Approx. device memory',`${navigator.deviceMemory} GB`,'device-memory');if(typeof navigator.cookieEnabled==='boolean')setMetric('Cookies enabled',navigator.cookieEnabled?'Yes':'No','cookies-enabled');updateConnectionMetrics();if(document.referrer)setMetric('Previous page',document.referrer,'referrer');if(Number.isFinite(history.length)&&history.length>0)setMetric('History length',String(history.length),'history-length');timeMetricValue=setMetric('Time of visit','00:00:00','time-of-visit');updateTimer();setInterval(updateTimer,250)}
function addPageLoadMetric(){try{const nav=performance.getEntriesByType('navigation')[0];if(nav&&Number.isFinite(nav.duration)&&nav.duration>0)setMetric('Page load time',`${Math.round(nav.duration)} ms`,'page-load-time')}catch(_){}}
function refreshLiveMetrics(){updateDisplayMetrics();updateAppearanceMetrics();updateConnectionMetrics();updateBatteryMetrics()}